name: like_this
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_custom_bottom_tab_bar:
    git: https://github.com/LiuC520/flutter_custom_bottom_tab_bar.git
  flutter_swiper: ^1.0.6
  dio: ^2.1.13
  flutter_easyrefresh: ^2.0.2
  json_serializable: ^2.0.0 # 解析
  transparent_image: ^0.1.0
  build_runner: ^1.1.2 # 解析
  fluttertoast: ^3.1.0
  flutter_screenutil: ^0.4.2
  flare_flutter: ^1.2.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  video_player: ^0.7.2
  flutter_ijkplayer: ^0.3.3
  flutter_picker:
    git: git://github.com/yangyxd/flutter_picker.git
  path_provider: ^0.5.0
  cached_network_image:
    git: https://github.com/tangtaoit/flutter_cached_network_image.git
  photo_view: ^0.4.2
  fake_tencent:
    git:
      url: https://github.com/v7lin/fake_tencent.git
  fluwx: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assert/imgs/tabbar_project_normal.png
    - assert/flare/Space.flr
    - assert/json/country_code_json.json
    - assert/imgs/tabbar_project_selected.png
    - assert/imgs/tabbar_home_normal.png
    - assert/imgs/message_like.png
    - assert/imgs/message_chat.png
    - assert/imgs/tapbar_home_selected.png
    - assert/imgs/tabbar_person_normal.png
    - assert/imgs/ic_add_normal.png
    - assert/imgs/tabbar_message_normal.png
    - assert/imgs/tabbar_message_selected.png
    - assert/imgs/ic_common_back.png
    - assert/imgs/loading.gif
    - assert/imgs/login_arrow_rightx.png
    - assert/imgs/closex.png
    - assert/imgs/login_qq.png
    - assert/imgs/login_wechat.png
    - assert/imgs/message_reply_arrow_right.png
    - assert/imgs/message_notice_arrow_right.png
    - assert/imgs/message_chat_arrow_right.png
    - assert/imgs/person_arrow_right_grayx.png
    - assert/imgs/message_thumb_arrow_right.png
    - assert/imgs/message_notice.png
    - assert/imgs/ic_square_add_user.png
    - assert/imgs/ic_square_search.png
    - assert/imgs/message_reply.png
    - assert/imgs/ic_photo.png
    - assert/imgs/tabbar_person_selected.png
    - assert/imgs/center_circle.png
    - assert/imgs/ic_main_tab_msg.png
    - assert/imgs/ic_main_tab_msg_pressed.png
    - assert/imgs/ic_user_collection.png
    - assert/imgs/ic_user_invite.png
    - assert/imgs/ic_user_post_collection.png
    - assert/imgs/ic_user_prize.png
    - assert/imgs/video_player.png
    - assert/imgs/ic_user_setting.png
    - assert/imgs/ic_user_view_history.png
    - assert/imgs/project_comics_new.png
    - assert/imgs/project_fans_new.png
    - assert/imgs/project_film_new.png
    - assert/imgs/project_game_new.png
    - assert/imgs/person_morex.png
    - assert/imgs/person_likex.png
    - assert/imgs/post_more.png
    - assert/imgs/person_share.png
    - assert/imgs/person_commentx.png
    - assert/imgs/arrow_down_refund.png
    - assert/imgs/icon_image_delete.png
